import {migrate,active,save,ageInfo,LANGUAGES,GOALS} from './profile.js';
import {recommend,domains} from './recommendations.js';
import {startCourse,sessionFor,completeCurrentStep,validateCourses} from './progression.js';
const app=document.querySelector('#app'),goalNames={chinese:'中文 / 语文',culture:'中华文化',science:'自然科学',geography:'地理',logic:'逻辑思维'};
let state={page:'home',filter:'all',store:null,profile:null,data:{courses:[],characters:[]},courseId:null,selected:null,score:0};
const e=s=>String(s||'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),name=()=>state.profile?.nickname||'小小探索家',age=()=>ageInfo(state.profile?.birthDate)?.label||'',initial=()=>Array.from(name())[0]||'★',course=()=>state.data.courses.find(x=>x.id===state.courseId)||recommend(state.data.courses,state.profile)[0];
const tags=()=>{let a=[];if(state.profile?.languages.includes('上海话'))a.push('上海话听说（即将推出）');if(state.profile?.languages.includes('英语'))a.push('中英辅助');return a};
const nav=()=>'<nav class="tabbar">'+[['home','首页'],['explore','探索'],['game','识字'],['print','活动'],['parent','家长']].map(x=>'<button class="tab '+(state.page===x[0]?'active':'')+'" data-go="'+x[0]+'"><i>⌂</i><span>'+x[1]+'</span></button>').join('')+'</nav>';
const card=c=>'<button class="course-card '+c.color+'" data-course="'+c.id+'"><div class="course-art">'+c.emoji+'</div><div><small>'+c.category+' · '+c.skills.join('、')+'</small><h2>'+c.title+'</h2><p>'+c.subtitle+'</p><em>'+c.age+'　·　'+c.language_support.map(x=>({mandarin:'普通话',shanghainese:'上海话',english:'英语'}[x])).join(' / ')+'</em></div><b>›</b></button>';
function profileForm(edit=false){let p=state.profile||{languages:[],learningGoals:[]};let checks=(arr,key,items)=>items.map(x=>'<label><input type="checkbox" name="'+key+'" value="'+x+'" '+(arr.includes(x)?'checked':'')+'><span>'+(goalNames[x]||x)+'</span></label>').join('');return '<section class="screen profile"><header class="profile-head"><span class="leaf">🌿</span><div><p>'+ (edit?'家长空间':'欢迎来到熹熹探索')+'</p><h1>'+ (edit?'编辑孩子资料':'先认识一下小小探索家')+'</h1></div></header><p class="profile-intro">昵称用于学习文案；其他项目可选，资料只保存在本机。</p><form id="profile-form" class="profile-form"><label>孩子昵称 / 姓名 <b>必填</b><input name="nickname" required value="'+e(p.nickname)+'"></label><label>出生日期 <span>建议填写</span><input name="birthDate" type="date" value="'+e(p.birthDate)+'"></label><label>性别 / 称呼偏好 <span>可选</span><select name="salutation"><option value="">暂不填写</option>'+['她','他','TA','不使用称呼'].map(x=>'<option '+(p.salutation===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label><fieldset><legend>家庭主要语言 <span>可多选</span></legend><div class="language-options">'+checks(p.languages,'languages',LANGUAGES)+'</div></fieldset><fieldset><legend>学习目标偏好 <span>可跳过，可多选</span></legend><div class="language-options">'+checks(p.learningGoals,'learningGoals',GOALS)+'</div></fieldset><button class="primary">'+(edit?'保存资料':'开始探索　→')+'</button></form>'+(edit?'<button class="text-button" data-go="parent">取消</button>':'')+'</section>'}
function home(){let r=recommend(state.data.courses,state.profile),t=tags();return '<section class="screen home"><header class="top"><div><p>早上好，'+name()+(age()?' · '+age():'')+'</p><h1>今天想发现什么？</h1></div><button class="avatar" data-go="parent">'+initial()+'</button></header><section class="hero"><div class="sparkles">✦　·　✦</div><p>和'+name()+'一起，<br><strong>发现身边的小秘密</strong></p><button class="pill light" data-go="explore">开始探索　→</button></section>'+ (t.length?'<div class="recommend-tags">'+t.map(x=>'<span>'+x+'</span>').join('')+'</div>':'')+'<div class="section-title"><h2>今日探索</h2><button data-go="explore">全部　›</button></div><p class="recommend-note">'+(state.profile.learningGoals.length?'根据学习目标推荐':'平衡推荐，家长可在资料中设置学习目标')+'</p>'+card(r[0])+'<div class="section-title"><h2>继续学习</h2></div>'+card(r[1]||r[0])+'</section>'}
function explore(){let r=recommend(state.data.courses,state.profile),shown=state.filter==='all'?state.data.courses:state.data.courses.filter(c=>c.domain===state.filter);return '<section class="screen"><header class="simple-head"><button class="back" data-go="home">‹</button><div><h1>探索小世界</h1><p>'+name()+'的推荐与全部内容</p></div></header><h2 class="subhead">为你推荐</h2><div class="course-list">'+r.slice(0,2).map(card).join('')+'</div><div class="section-title"><h2>按领域浏览</h2></div><div class="chips">'+Object.entries(domains).map(([k,v])=>'<button class="'+(state.filter===k?'chosen':'')+'" data-filter="'+k+'">'+v+'</button>').join('')+'</div><div class="course-list">'+shown.map(card).join('')+'</div></section>'}
function detail(){let c=course();return '<section class="screen detail '+c.color+'"><header class="detail-head"><button class="back" data-go="explore">‹</button><span>'+c.category+'</span></header><div class="detail-hero"><div class="giant-art">'+c.emoji+'</div></div><article class="sheet"><p class="eyebrow">'+c.category+'</p><h1>'+c.title+'</h1><p class="intro">'+c.subtitle+'</p><div class="meta"><span>适合 '+c.age+'</span><span>'+c.skills.join(' · ')+'</span></div><h2>我们会发现</h2><div class="steps">'+c.steps.map((s,i)=>'<div><b>'+(i+1)+'</b><span>'+s.emoji+'</span><p><strong>'+s.title+'</strong>'+s.body+'</p></div>').join('')+'</div><button class="primary" data-start>和'+name()+'一起开始　→</button><button class="secondary" data-print>▧　打印延伸活动</button></article></section>'}
function sceneMarkup(scene){const elements=scene.elements.join(' ');if(scene.type==='seed_growth')return '<div class="scene seed-scene" data-scene="'+scene.asset_id+'"><span class="scene-sun">☀</span><span class="scene-soil">土壤</span><span class="scene-main">'+(elements.includes('sprout')?'🌱':'🌰')+'</span>'+(elements.includes('water')?'<span class="scene-water">💧</span>':'')+'</div>';if(scene.type==='light_shadow')return '<div class="scene shadow-scene" data-scene="'+scene.asset_id+'"><span class="scene-lamp">🔦</span><span class="scene-object">'+(elements.includes('hand')?'✋':'🧸')+'</span><span class="scene-shadow">◢</span></div>';return '<div class="scene neutral-scene" data-scene="'+scene.asset_id+'"><span>'+({character_focus:'日',moon_story:'🌕',map_direction:'🧭',shape_sort:'🔺'}[scene.type]||'✨')+'</span></div>'}
function lesson(){let c=course(),session=sessionFor(c.id)||startCourse(c.id),s=c.steps[session.stepIndex];return '<section class="screen lesson"><header class="lesson-head"><button class="back" data-go="detail">‹</button><span><small>'+ (session.stepIndex+1)+' / '+c.steps.length+'</small></span><button class="close" data-go="explore">×</button></header>'+sceneMarkup(s.scene)+'<article class="lesson-copy"><p class="eyebrow">第'+(session.stepIndex+1)+'站</p><h1>'+s.title+'</h1><p>'+name()+'，'+s.body+'</p><button class="primary" data-next-step>'+ (session.stepIndex===c.steps.length-1?'完成探索　→':'我知道啦　→')+'</button></article></section>'}
function game(){let chars=state.data.characters;return '<section class="screen game"><header class="simple-head"><button class="back" data-go="home">‹</button><div><h1>汉字小侦探</h1><p>'+name()+'，找到和图片一样的字</p></div><span class="star-count">★ '+state.score+'</span></header><div class="game-scene"><div class="sun-card">☀️</div></div><div class="game-prompt"><strong>太阳</strong></div><div class="character-options">'+chars.map(c=>'<button class="character '+(state.selected===c.id?'selected':'')+'" data-char="'+c.id+'"><b>'+c.hanzi+'</b><small>'+c.pinyin+'</small></button>').join('')+'</div><button class="primary game-check" data-check '+(state.selected?'':'disabled')+'>确定</button></section>'}
function printPage(){let c=course();return '<section class="screen print"><header class="simple-head"><button class="back" data-go="home">‹</button><div><h1>亲子活动</h1><p>把探索带到现实生活里</p></div></header><div class="print-feature"><div class="paper-preview"><span>'+c.emoji+'</span><b>'+c.printable.title+'</b></div><div><small>推荐打印</small><h2>'+c.printable.title+'</h2><p>'+c.printable.description+'</p><button class="primary" data-print>打印活动单</button></div></div></section>'}
function parent(){let p=state.profile;return '<section class="screen parent"><header class="simple-head"><button class="back" data-go="home">‹</button><div><h1>家长空间</h1><p>陪伴每一次小小的成长</p></div></header><section class="child-card"><div class="child-avatar">'+initial()+'</div><div><small>'+name()+'的探索旅程'+(age()?' · '+age():'')+'</small><h2>本周已经探索 2 次</h2></div></section><section class="profile-summary"><div><p>孩子资料</p><strong>'+name()+'</strong><span>'+(p.languages.join('、')||'未填写语言')+'</span><small>学习目标：'+(p.learningGoals.map(x=>goalNames[x]).join('、')||'平衡推荐')+'</small></div><button data-edit>编辑　›</button></section><h2 class="subhead">本周发现</h2><div class="stats"><div><b>2</b><span>探索课程</span></div><div><b>1</b><span>认识汉字</span></div><div><b>3</b><span>获得星星</span></div></div></section>'}
function render(){let pages={home,explore,detail,lesson,game,print:printPage,parent,profile:()=>profileForm(),'edit-profile':()=>profileForm(true)};app.innerHTML=pages[state.page]()+(!['detail','lesson','profile','edit-profile'].includes(state.page)?nav():'')+'<div id="toast"></div>'}
function toast(x){let t=document.querySelector('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
app.addEventListener('submit',ev=>{if(ev.target.id!=='profile-form')return;ev.preventDefault();let p=save(state.store,ev.target);if(p){state.profile=p;state.page='parent';render();toast('孩子资料已保存')}});app.addEventListener('click',ev=>{let x=ev.target.closest('[data-go]');if(x){state.page=x.dataset.go;render();return}x=ev.target.closest('[data-filter]');if(x){state.filter=x.dataset.filter;render();return}if(ev.target.closest('[data-edit]')){state.page='edit-profile';render();return}x=ev.target.closest('[data-course]');if(x){state.courseId=x.dataset.course;state.page='detail';render();return}if(ev.target.closest('[data-start]')){startCourse(course().id);state.page='lesson';render();return}if(ev.target.closest('[data-next-step]')){let c=course(),next=completeCurrentStep(c);if(next.status==='complete'){state.page='explore';toast('探索完成啦！')}render();return}x=ev.target.closest('[data-char]');if(x){state.selected=x.dataset.char;render();return}if(ev.target.closest('[data-check]')){if(state.selected==='sun'){state.score++;toast('答对啦！');}else toast('再想一想～');state.selected=null;render();return}if(ev.target.closest('[data-print]'))window.print()});
async function boot(){state.data=await fetch('./data/courses.json').then(r=>r.json());const errors=validateCourses(state.data.courses);if(errors.length)throw new Error('Course scene invariant failed: '+errors.join(', '));state.store=migrate();state.profile=active(state.store);if(!state.profile)state.page='profile';render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')}boot();
