import {migrate,active,save,ageInfo,LANGUAGES,GOALS} from './profile.js';
import {recommend,domains} from './recommendations.js';
import {startCourse,sessionFor,completeCurrentStep,validateCourses} from './progression.js';
import {migrateLearning,recordAttempt,reviewQueue,continueCourses,printableState,selectMigrationRuntimeState} from './learning.js';
import {sceneMarkup,activityLabel,optionsMarkup,activityExtraMarkup} from './presentation.js';
const app=document.querySelector('#app'),goalNames={chinese:'中文 / 语文',culture:'中华文化',science:'自然科学',geography:'地理',logic:'逻辑思维'};
let state={page:'home',filter:'all',store:null,profile:null,data:{courses:[],activities:[],skills:[],printables:[]},courseId:null,selected:null,feedback:null};
const e=s=>String(s||'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const name=()=>state.profile?.nickname||'小小探索家',age=()=>ageInfo(state.profile?.birthDate)?.label||'',course=()=>state.data.courses.find(x=>x.id===state.courseId),activity=id=>state.data.activities.find(x=>x.id===id),printable=id=>state.data.printables.find(x=>x.id===id),skill=id=>state.data.skills.find(x=>x.id===id);
const nav=()=>'<nav class="tabbar">'+[['home','首页'],['explore','探索'],['game','识字'],['print','活动'],['parent','家长']].map(([id,label])=>'<button class="tab '+(state.page===id?'active':'')+'" data-go="'+id+'"><span>'+label+'</span></button>').join('')+'</nav>';
const card=c=>'<button class="course-card '+c.color+'" data-course="'+c.id+'"><div class="course-art">'+c.emoji+'</div><div><small>'+c.category+'</small><h2>'+c.title+'</h2><p>'+c.subtitle+'</p><em>'+c.age+'</em></div><b>›</b></button>';
function profileForm(edit=false){let p=state.profile||{languages:[],learningGoals:[]},checks=(arr,key,items)=>items.map(x=>'<label><input type="checkbox" name="'+key+'" value="'+x+'" '+(arr.includes(x)?'checked':'')+'><span>'+(goalNames[x]||x)+'</span></label>').join('');return '<section class="screen profile"><header class="profile-head"><div><p>'+ (edit?'家长空间':'欢迎来到探索')+'</p><h1>'+ (edit?'编辑孩子资料':'先认识一下小小探索家')+'</h1></div></header><form id="profile-form" class="profile-form"><label>孩子昵称 / 姓名 <b>必填</b><input name="nickname" required value="'+e(p.nickname)+'"></label><label>出生日期 <span>建议填写</span><input name="birthDate" type="date" value="'+e(p.birthDate)+'"></label><label>性别 / 称呼偏好 <select name="salutation"><option value="">暂不填写</option>'+['她','他','TA','不使用称呼'].map(x=>'<option '+(p.salutation===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label><fieldset><legend>家庭主要语言</legend><div class="language-options">'+checks(p.languages,'languages',LANGUAGES)+'</div></fieldset><fieldset><legend>学习目标偏好</legend><div class="language-options">'+checks(p.learningGoals,'learningGoals',GOALS)+'</div></fieldset><button class="primary">'+(edit?'保存资料':'开始探索　→')+'</button></form></section>'}
function home(){let r=recommend(state.data.courses,state.profile),ongoing=continueCourses(state.data.courses),reviews=reviewQueue();return '<section class="screen home"><header class="top"><div><p>早上好，'+name()+(age()?' · '+age():'')+'</p><h1>今天想发现什么？</h1></div><button class="avatar" data-go="parent">'+e(name()[0])+'</button></header><section class="hero"><p>和'+name()+'一起，<br><strong>发现身边的小秘密</strong></p><button class="pill light" data-go="explore">开始探索　→</button></section>'+(ongoing.length?'<div class="section-title"><h2>继续学习</h2></div>'+ongoing.map(x=>'<button class="continue-card" data-resume="'+x.course.id+'">'+x.course.title+'<small>已完成 '+x.progress.stepIndex+'/'+x.course.steps.length+'　继续 ›</small></button>').join(''):'')+(reviews.length?'<div class="section-title"><h2>需要复习</h2></div>'+reviews.map(x=>'<button class="continue-card" data-review="'+x.skillId+'">'+(skill(x.skillId)?.character||skill(x.skillId)?.meaning||x.skillId)+'<small>轻轻复习一下　›</small></button>').join(''):'')+'<div class="section-title"><h2>今日探索</h2><button data-go="explore">全部　›</button></div><p class="recommend-note">'+(state.profile.learningGoals.length?'根据学习目标推荐':'平衡推荐')+'</p>'+card(r[0])+'</section>'}
function explore(){let r=recommend(state.data.courses,state.profile),shown=state.filter==='all'?state.data.courses:state.data.courses.filter(c=>c.domain===state.filter);return '<section class="screen"><header class="simple-head"><button class="back" data-go="home">‹</button><div><h1>探索小世界</h1><p>'+name()+'的推荐与全部内容</p></div></header><h2 class="subhead">为你推荐</h2><div class="course-list">'+r.slice(0,3).map(card).join('')+'</div><div class="chips">'+Object.entries(domains).map(([k,v])=>'<button class="'+(state.filter===k?'chosen':'')+'" data-filter="'+k+'">'+v+'</button>').join('')+'</div><div class="course-list">'+shown.map(card).join('')+'</div></section>'}
function detail(){let c=course(),p=sessionFor(c.id);return '<section class="screen detail '+c.color+'"><header class="detail-head"><button class="back" data-go="explore">‹</button></header><div class="detail-hero"><div class="giant-art">'+c.emoji+'</div></div><article class="sheet"><p>'+c.category+'</p><h1>'+c.title+'</h1><p>'+c.subtitle+'</p><div class="steps">'+c.steps.map((s,i)=>'<div><b>'+(i+1)+'</b><p>'+activity(s.activity_id).title+'</p></div>').join('')+'</div><button class="primary" data-start>'+((p?.status==='active')?'继续学习':'和'+name()+'一起开始')+'　→</button><button class="secondary" data-print-id="'+c.printable_id+'">▧　打印延伸活动</button></article></section>'}
function lesson(){let c=course(),p=sessionFor(c.id)||startCourse(c.id),step=c.steps[p.stepIndex],a=activity(step.activity_id),gentle=['speak','real_world','info','printable','trace'].includes(a.activity_type);let action=gentle?'<button class="primary lesson-action" data-complete-gentle>'+(a.activity_type==='printable'?'我看过活动单了':'我完成啦　→')+'</button>':'<button class="primary lesson-action" data-check '+(state.selected?'':'disabled')+'>看看答案</button>';if(state.feedback===true)action='<div class="feedback good" role="status"><span class="feedback-symbol">✓</span><div><strong>真棒，发现了！</strong><p>'+e(a.correct_feedback||'你认真完成了这一步。')+'</p></div></div><button class="primary lesson-action" data-next-step>'+(p.stepIndex===c.steps.length-1?'完成探索　→':'下一步　→')+'</button>';if(state.feedback===false)action='<div class="feedback try" role="status"><span class="feedback-symbol">↺</span><div><strong>再观察一下</strong><p>'+e(a.incorrect_feedback||'没关系，再试试看。')+'</p></div></div><button class="secondary retry-action" data-retry>换一个试试</button>';return '<section class="screen lesson theme-'+e(c.domain)+'"><header class="lesson-head"><button class="back" data-go="detail" aria-label="返回课程">‹</button><div class="lesson-progress"><small>'+e(c.title)+'</small><span>第 '+(p.stepIndex+1)+' / '+c.steps.length+' 步</span><div class="step-track"><i style="width:'+((p.stepIndex+1)/c.steps.length*100)+'%"></i></div></div><button class="close" data-go="explore" aria-label="退出课程">×</button></header>'+sceneMarkup(a)+'<article class="lesson-copy"><p class="lesson-kicker">'+activityLabel(a.activity_type)+'</p><h1>'+e(a.title)+'</h1><p class="lesson-body">'+e(a.body)+'</p>'+(a.audio_text?'<button class="audio-card" data-audio><span class="audio-icon">♪</span><span>点一下，听一听</span><strong>播放语音</strong></button>':'')+activityExtraMarkup(a)+optionsMarkup(a,state.selected,state.feedback)+action+'</article></section>'}
function printPage(){let all=state.data.printables;return '<section class="screen print"><header class="simple-head"><button class="back" data-go="home">‹</button><div><h1>亲子活动</h1><p>把探索带到现实生活里</p></div></header>'+all.map(p=>'<div class="print-feature"><div class="paper-preview">▧</div><div><small>'+p.domain+'</small><h2>'+p.title+'</h2><p>'+p.description+'</p><button class="primary" data-print-id="'+p.id+'">打印活动单</button></div></div>').join('')+'</section>'}
function parent(){let p=state.profile;return '<section class="screen parent"><header class="simple-head"><button class="back" data-go="home">‹</button><div><h1>家长空间</h1><p>陪伴每一次小小的成长</p></div></header><section class="child-card"><div class="child-avatar">'+e(name()[0])+'</div><div><small>'+name()+'的探索旅程'+(age()?' · '+age():'')+'</small><h2>学习记录会保存在本机</h2></div></section><section class="profile-summary"><div><p>孩子资料</p><strong>'+name()+'</strong><span>'+(p.languages.join('、')||'未填写语言')+'</span></div><button data-edit>编辑　›</button></section></section>'}
function setupTraceCanvas(){const canvas=app.querySelector('.trace-canvas');if(!canvas)return;const rect=canvas.getBoundingClientRect(),scale=devicePixelRatio||1;canvas.width=Math.round(rect.width*scale);canvas.height=Math.round(rect.height*scale);const ink=canvas.getContext('2d');ink.scale(scale,scale);ink.strokeStyle='#c36f51';ink.lineWidth=8;ink.lineCap='round';ink.lineJoin='round';let drawing=false;const point=event=>{const bounds=canvas.getBoundingClientRect();return{x:event.clientX-bounds.left,y:event.clientY-bounds.top}};canvas.addEventListener('pointerdown',event=>{drawing=true;canvas.setPointerCapture(event.pointerId);const p=point(event);ink.beginPath();ink.moveTo(p.x,p.y);ink.lineTo(p.x+.1,p.y+.1);ink.stroke()});canvas.addEventListener('pointermove',event=>{if(!drawing)return;const p=point(event);ink.lineTo(p.x,p.y);ink.stroke()});canvas.addEventListener('pointerup',()=>drawing=false);canvas.addEventListener('pointercancel',()=>drawing=false)}
function render(){let pages={home,explore,detail,lesson,game:()=>'<section class="screen"><h1>汉字小侦探</h1><p>从“认识春”开始，体验六种中文活动。</p><button class="primary" data-course="chinese.spring">开始识字</button></section>',print:printPage,parent,profile:()=>profileForm(), 'edit-profile':()=>profileForm(true)};app.innerHTML=pages[state.page]()+(!['detail','lesson','profile','edit-profile'].includes(state.page)?nav():'');if(state.page==='lesson')setupTraceCanvas()}
app.addEventListener('submit',ev=>{if(ev.target.id!=='profile-form')return;ev.preventDefault();let p=save(state.store,ev.target);if(p){state.profile=p;state.page='parent';render()}});
app.addEventListener('click',ev=>{
  let x=ev.target.closest('[data-go]');if(x){state.page=x.dataset.go;state.selected=null;state.feedback=null;render();return}
  x=ev.target.closest('[data-filter]');if(x){state.filter=x.dataset.filter;render();return}
  if(ev.target.closest('[data-edit]')){state.page='edit-profile';render();return}
  x=ev.target.closest('[data-course]');if(x){state.courseId=x.dataset.course;state.page='detail';state.selected=null;state.feedback=null;render();return}
  x=ev.target.closest('[data-resume]');if(x){state.courseId=x.dataset.resume;state.page='lesson';state.selected=null;state.feedback=null;render();return}
  x=ev.target.closest('[data-review]');if(x){let c=state.data.courses.find(c=>c.skills.includes(x.dataset.review));state.courseId=c?.id||'chinese.spring';startCourse(state.courseId);state.page='lesson';state.selected=null;state.feedback=null;render();return}
  if(ev.target.closest('[data-start]')){startCourse(course().id);state.page='lesson';state.selected=null;state.feedback=null;render();return}
  x=ev.target.closest('[data-answer]');if(x&&state.feedback!==true){state.selected=x.dataset.answer;state.feedback=null;render();return}
  if(ev.target.closest('[data-retry]')){state.selected=null;state.feedback=null;render();return}
  if(ev.target.closest('[data-clear-trace]')){const canvas=app.querySelector('.trace-canvas');canvas?.getContext('2d')?.clearRect(0,0,canvas.width,canvas.height);return}
  if(ev.target.closest('[data-audio]')){let a=activity(course().steps[(sessionFor(course().id)||startCourse(course().id)).stepIndex].activity_id);speechSynthesis?.speak(new SpeechSynthesisUtterance(a.audio_text));return}
  if(ev.target.closest('[data-check]')){let p=sessionFor(course().id),a=activity(course().steps[p.stepIndex].activity_id);state.feedback=state.selected===a.answer;recordAttempt(a.skill_id,state.feedback);render();return}
  if(ev.target.closest('[data-complete-gentle]')){let p=sessionFor(course().id),a=activity(course().steps[p.stepIndex].activity_id);if(a.activity_type==='printable')printableState(a.printable_id,'viewed');else recordAttempt(a.skill_id,true);state.feedback=true;render();return}
  if(ev.target.closest('[data-next-step]')){completeCurrentStep(course());state.selected=null;state.feedback=null;if(sessionFor(course().id).status==='complete')state.page='explore';render();return}
  x=ev.target.closest('[data-print-id]');if(x){printableState(x.dataset.printId,'viewed');window.print();return}
});
const emptyMigrationRuntime=()=>({migrationId:null,fromVersion:null,toVersion:null,completed:false,completedAt:null,warnings:[],warningsCount:0});
function syncMigrationRuntimeState(){window.__XIXI_MIGRATION__=selectMigrationRuntimeState()||emptyMigrationRuntime();return window.__XIXI_MIGRATION__}
async function loadContent(){const [courses,activities,skills,printables]=await Promise.all(['courses','activities','skills','printables'].map(x=>fetch('./data/'+x+'.json').then(r=>r.json())));state.data={courses:courses.courses,activities:activities.activities,skills:skills.skills,printables:printables.printables};const errors=validateCourses(state.data.courses,state.data.activities);if(errors.length)throw new Error(errors.join('; '))}
function initializeCanonicalState(){state.store=migrate();migrateLearning();syncMigrationRuntimeState();state.profile=active(state.store)}
function renderInitialUI(){if(!state.profile)state.page='profile';render()}
async function boot(){window.__XIXI_APP_READY__=false;window.__XIXI_MIGRATION_PHASE__='checking';await loadContent();window.__XIXI_MIGRATION_PHASE__='running';initializeCanonicalState();window.__XIXI_MIGRATION_PHASE__='complete';renderInitialUI();window.__XIXI_APP_VERSION__='0.4.0-rc2';window.__XIXI_APP_READY__=true;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none',scope:'./'})}
boot();
