const KEY='xixi-learning-progress',MIGRATIONS='xixi-migrations',DIAGNOSTICS='xixi-migration-diagnostics';
const now=()=>new Date().toISOString();
const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
const write=x=>localStorage.setItem(KEY,JSON.stringify(x));
export const legacyCourseIdMap=Object.freeze({'seed-journey':'science.seed-journey','shadow-play':'science.shadow-magic','mid-autumn':'culture.festival.mid_autumn','sun-character':'chinese.spring'});
const migrationMeta=()=>read(MIGRATIONS)||{};
export function selectMigrationRuntimeState(){const metadata=migrationMeta()['0.3.1-to-0.4.0'];const diagnostics=read(DIAGNOSTICS)||{warnings:[]};return metadata?{migrationId:metadata.migrationId,fromVersion:metadata.fromVersion,toVersion:metadata.toVersion,completed:metadata.completed,completedAt:metadata.completedAt,warnings:diagnostics.warnings||[],warningsCount:(diagnostics.warnings||[]).length}:{migrationId:null,fromVersion:null,toVersion:null,completed:false,completedAt:null,warnings:[],warningsCount:0}}
export function migrateLegacyProgress(legacyRecord,{legacyCourseId}){const courseId=legacyCourseIdMap[legacyCourseId]||Object.values(legacyCourseIdMap).includes(legacyCourseId)&&legacyCourseId;if(!courseId)return{warning:{legacyCourseId,reason:'unknown legacy course',timestamp:now()},legacyRecord};const completed=legacyRecord.status==='complete'||!!legacyRecord.completedAt;const status=completed?'complete':'learning';return{record:{...legacyRecord,courseId,status,stepIndex:Number.isInteger(legacyRecord.stepIndex)?legacyRecord.stepIndex:0,updatedAt:legacyRecord.updatedAt||legacyRecord.completedAt||now()},courseId,defaultedFields:legacyRecord.updatedAt?[]:['updatedAt']}}
export function migrateLearning(){let value=read(KEY);if(value?.version===1)return value;const prior=migrationMeta(),legacy=read('xixi-course-progress')||{},warnings=[],unmapped={},courses={},legacyEntries=Object.entries(legacy);value={version:1,courses,skills:{},printables:{}};if(!legacyEntries.length){write(value);return value}for(const [legacyCourseId,legacyRecord] of legacyEntries){const result=migrateLegacyProgress(legacyRecord,{legacyCourseId});if(result.warning){warnings.push(result.warning);unmapped[legacyCourseId]=result.legacyRecord;continue}const existing=courses[result.courseId];if(existing){const choose=result.record.status==='complete'||existing.status!=='complete'?result.record:existing;courses[result.courseId]=choose;warnings.push({legacyCourseId,reason:'duplicate canonical course merged',timestamp:now()})}else courses[result.courseId]=result.record}write(value);if(!prior['0.3.1-to-0.4.0']){const metadata={fromVersion:'0.3.1',toVersion:'0.4.0',completed:true,completedAt:now(),migrationId:'0.3.1-to-0.4.0'};localStorage.setItem(MIGRATIONS,JSON.stringify({...prior,[metadata.migrationId]:metadata}));localStorage.setItem(DIAGNOSTICS,JSON.stringify({warnings,unmapped}))}return value}
export const learning=()=>migrateLearning();
export function courseProgress(courseId){return learning().courses[courseId]||null}
export function beginCourse(courseId){const store=learning(),old=store.courses[courseId];if(old?.status==='active')return old;const next={courseId,stepIndex:0,status:'active',startedAt:now(),updatedAt:now()};store.courses[courseId]=next;write(store);return next}
export function completeStep(course){const store=learning(),p=store.courses[course.id]||beginCourse(course.id);if(p.stepIndex<course.steps.length-1)p.stepIndex++;else{p.status='complete';p.completedAt=now()}p.updatedAt=now();store.courses[course.id]=p;write(store);return p}
export function recordAttempt(skillId,correct){const store=learning(),s=store.skills[skillId]||{skillId,attempts:[],status:'not_started'};s.attempts.push({correct:!!correct,at:now()});s.attempts=s.attempts.slice(-20);const last=s.attempts.slice(-2),accuracy=s.attempts.filter(x=>x.correct).length/s.attempts.length;s.status=s.attempts.length>=3&&last.length===2&&last.every(x=>x.correct)&&accuracy>=.67?'mastered':(!correct&&s.status==='mastered'?'needs_review':'learning');s.updatedAt=now();store.skills[skillId]=s;write(store);return s}
export function refreshReview(nowDate=new Date()){const store=learning();for(const s of Object.values(store.skills)){if(s.status==='mastered'&&s.updatedAt&&(nowDate-new Date(s.updatedAt))>=3*864e5)s.status='needs_review'}write(store);return store}
export function reviewQueue(limit=3){const store=refreshReview();return Object.values(store.skills).filter(x=>x.status==='needs_review').slice(0,limit)}
export function continueCourses(courses){const store=learning();return courses.filter(c=>['active','learning'].includes(store.courses[c.id]?.status)).map(c=>({course:c,progress:store.courses[c.id]}))}
export function printableState(id,action){const store=learning(),p=store.printables[id]||{};if(action)p[action]=now();store.printables[id]=p;write(store);return p}
